# Generated by Django 4.1.1 on 2022-10-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinda_food_trucks', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='truck',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='truck',
            name='applicant',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='truck',
            name='facilitytype',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='truck',
            name='latitude',
            field=models.FloatField(default=0.0, max_length=200),
        ),
        migrations.AddField(
            model_name='truck',
            name='locationdescription',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='truck',
            name='longitude',
            field=models.FloatField(default=0.0, max_length=200),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.TextField(default=' '),
        ),
    ]
